## Settings
title: pRoJEct-NeGYa
owner: "zhaoey"
url: "https://zhaoey.github.io"
baseurl: "/pRoJEct-NeGYa"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "cn.zhaoey@gmail.com"
github: "zhaoeryu/pRoJEct-NeGYa"

statement: "Designed by DeerRIDER, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
